In [2]:
import numpy as np
import math as mt

In [ ]:
array1 = np.arange(1,11,1)
print(f"Array de 1 a 10 : {array1}")

array_pares = np.arange(2,22,2)
print(f"Array de 1 a 10 : {array_pares}")

array_zeros = np.zeros(5)
print(f"Array de 0 : {array_zeros}")

array_setes = np.full(5,7)
print(f"Array de 7 : {array_setes}")

numeros = np.array([10, 20, 30, 40, 50])
print(f"Array base : {numeros}")

soma = np.sum(numeros)
print(f"Soma elementos : {soma}")

media = np.mean(numeros)
print(f"Media array : {media:.2f}")

maximo = max(numeros)
minimo = min(numeros)
print(f"Máximo valor : {maximo}")
print(f"Mínimo  valor : {minimo}")
print(f"Tamanho array : {len(numeros)}")


Array de 1 a 10 : [ 1  2  3  4  5  6  7  8  9 10]
Array de 1 a 10 : [ 2  4  6  8 10 12 14 16 18 20]
Array de 0 : [0. 0. 0. 0. 0.]
Array de 7 : [7 7 7 7 7]
Array base : [10 20 30 40 50]
Soma elementos : 150
Media array : 30.00
Máximo valor : 50
Mínimo  valor : 10
Tamanho array : 5


In [16]:
notas = np.array([7, 8.5, 6, 9, 5.5, 10])

print(f"Primeira nota : {notas[0]}")
print(f"última nota : {notas[5]}")
print(f"Três primeiras notas : {notas[0:3]}")
print(f"Notas posições 2,3 e 4 respecitvamente : {notas[2]},{notas[3]},{notas[4]}")
notas[4] = 6
print(f"Notas após update : {notas}")


Primeira nota : 7.0
última nota : 10.0
Três primeiras notas : [7.  8.5 6. ]
Notas posições 2,3 e 4 respecitvamente : 6.0,9.0,5.5
Notas após update : [ 7.   8.5  6.   9.   6.  10. ]


In [3]:
numbers = np.array([5, 12, 8, 20, 3, 15, 7, 30])
condi = numbers>10
maiores = numbers[condi]
print(f"Vetor maiores que 10 : {maiores}")

notas2 = np.array([4, 7, 8.5, 5, 9, 3, 6, 10])
condicao = notas2>6
maiores = numbers[condicao]
print(f"Alunos aprovados : {len(maiores)}")
print(f"Média aprovados : {np.mean(maiores)}")


nums = np.array([1, 4, 7, 10, 13, 16, 20, 25])
condition = nums%2==0
pares = nums[condition]
print(f"Apenas pares : {pares}")




Vetor maiores que 10 : [12 20 15 30]
Alunos aprovados : 4
Média aprovados : 13.25
Apenas pares : [ 4 10 16 20]


In [11]:
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f"Primeria linha : {matriz[0,:]} ")
print(f"Segunda coluna : {matriz[:,1]} ")
print(f"Elemento 1x1 : {matriz[1,1]} ")
print(f"Primeiro quadrante {matriz[0:2,0:2]}")
print(f"Soma dos elementos : {np.sum(matriz)}")
print(f"Media dos elementos : {np.mean(matriz)}")


print(f"Soma linhas : {np.sum(matriz,axis=1)}")
print(f"Soma colunas : {np.sum(matriz,axis=0)}")




Primeria linha : [1 2 3] 
Segunda coluna : [2 5 8] 
Elemento 1x1 : 5 
Primeiro quadrante [[1 2]
 [4 5]]
Soma dos elementos : 45
Media dos elementos : 5.0
Soma linhas : [ 6 15 24]
Soma colunas : [12 15 18]


In [22]:
notas = np.array([
    [7, 8, 9],
    [5, 6, 4],
    [10, 9, 8],
    [6, 7, 5]
])

print(f"Media alunos : {notas.mean(axis=1)}")
print(f"Maior media : {max(notas.mean(axis=1))}")
print(f"Aluno maior média : {2}")
print(f"Media provas : {notas.mean(axis=0)}")

condicao = notas.mean(axis=1) >= 6

aprovados = notas[condicao]

print(f"Alunos aprovados(linha==aluno,coluna==nota na prova) : \n{aprovados}")



Media alunos : [8. 5. 9. 6.]
Maior media : 9.0
Aluno maior média : 2
Media provas : [7.  7.5 6.5]
Alunos aprovados(linha==aluno,coluna==nota na prova) : 
[[ 7  8  9]
 [10  9  8]
 [ 6  7  5]]
