Aula 4 - Numpy

-Usa estrutura própria ndArray(Numpy Array), usa normalmente tuplas e listas

-Numpy é muito otimizado(usa C no backend)

In [36]:
import numpy as np
#Importando biblioteca numpy

In [37]:
arr = np.array([10,20,30,40,50,60])
print(type(arr))
print(arr)
print(f"tamanho array : {arr.size}")
print(f"Dimensões do array(1,2,3) : {arr.ndim}")
print(f"Formato do array(3 x 2, 1 x 0) : {arr.shape} ")

mtz = np.array([[10,20],
                [30,40],
                [50,60]])
print(type(mtz))
print(f"Matriz : \n{mtz}")
print(f"tamanho matriz : {mtz.size}")
print(f"Dimensões da matriz : {mtz.ndim}")
print(f"Formato da matriz : {mtz.shape}")

<class 'numpy.ndarray'>
[10 20 30 40 50 60]
tamanho array : 6
Dimensões do array(1,2,3) : 1
Formato do array(3 x 2, 1 x 0) : (6,) 
<class 'numpy.ndarray'>
Matriz : 
[[10 20]
 [30 40]
 [50 60]]
tamanho matriz : 6
Dimensões da matriz : 2
Formato da matriz : (3, 2)


Funções pré-prontas

In [38]:
mtz = np.ones([5,5])
print(f"Matriz de um :  \n{mtz}")

mtz_zeros = np.zeros([5,5])
print(f"Matriz de zeros : \n{mtz_zeros}")

mtz_eye = np.eye(5)
print(f"Matriz identidade : \n{mtz_eye}")

arr = np.zeros([10])
print(arr.reshape([5,2]))

print(f"Array : {arr}")
print(f"Array transformado em matriz : {arr}")

mtz = np.arange(2,21,2)
print(f"Array de 2 a 20 de 2 em 2 : {mtz}")

print(f"Array transformado em matriz :  \n{mtz.reshape(2,5)}")




Matriz de um :  
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Matriz de zeros : 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Matriz identidade : 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Array : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array transformado em matriz : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array de 2 a 20 de 2 em 2 : [ 2  4  6  8 10 12 14 16 18 20]
Array transformado em matriz :  
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


Operações entre Numpy arrays

In [39]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([1,2,3,4,5])

print(f"Soma : {arr1 + arr2}") # ou arr3 = arr1 + arr2
print(f"Subtração : {arr1 - arr2}")
print(f"Multiplicação : {arr1 * arr2}")
print(f"Divisão : {arr1 / arr2}")
print(f"Potência : {arr1 ** arr2}")
print(f"Raiz quadrada : {np.sqrt(arr1)}")
print(f"Exponencial : {np.exp(arr1)}")
print(f"Logaritmo : {np.log(arr1)}")

arr3 = np.concatenate([arr1,arr2])
print(f"Arrays concatenados : {arr3}")

print(f"Escalar vezes o array : {2 * arr1}") # Broadcasting







Soma : [11 22 33 44 55]
Subtração : [ 9 18 27 36 45]
Multiplicação : [ 10  40  90 160 250]
Divisão : [10. 10. 10. 10. 10.]
Potência : [       10       400     27000   2560000 312500000]
Raiz quadrada : [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Exponencial : [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
Logaritmo : [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
Arrays concatenados : [10 20 30 40 50  1  2  3  4  5]
Escalar vezes o array : [ 20  40  60  80 100]


In [40]:
mtz = np.arange(10,96,5)
print(f"Array gerado : {mtz}")
print(f"Array transformada em matriz  : \n{mtz.reshape(3,6)}")
mtz = mtz.reshape(3,6)

#Extraindo soma das colunas
print(f"Soma colunas  : {mtz.sum(axis=0)}")

print(f"Soma linhas  : {mtz.sum(axis=1)}")

print(f"Soma primeira coluna : {mtz.sum(axis=0)[0]}")

print(f"Soma segunda linha : {mtz.sum(axis=1)[1]}")

print(f"Média das colunas : {mtz.mean(axis=0)}")

print(f"Média das linhas : {mtz.mean(axis=1)}")

print(f"Pegando soma de segunda coluna em diante : {mtz.sum(axis = 0)[1:,]}")

print(f"Pegando soma de segunda linha em diante : {mtz.sum(axis = 1)[1:,]}")







Array gerado : [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
Array transformada em matriz  : 
[[10 15 20 25 30 35]
 [40 45 50 55 60 65]
 [70 75 80 85 90 95]]
Soma colunas  : [120 135 150 165 180 195]
Soma linhas  : [135 315 495]
Soma primeira coluna : 120
Soma segunda linha : 315
Média das colunas : [40. 45. 50. 55. 60. 65.]
Média das linhas : [22.5 52.5 82.5]
Pegando soma de segunda coluna em diante : [135 150 165 180 195]
Pegando soma de segunda linha em diante : [315 495]


Núemros aleatórios no Numpy

In [41]:
np.random.seed(5)
#Coloca uma semente que garante que os números serão os mesmos para todas máquinas
arr = np.random.randint(10)
print(f"Gerando número aleatório entre 0 e 10 : {arr}")

arr = np.random.randint(1,10,10)

print(f"Delimitando o sorteio(1 a 10,10 números) : {arr}")

print(f"Transformando em um conjunto : {set(arr)}")

print(f"Transformando em um conjunto(usando numpy) : {np.unique(arr)} ")

elementos_unicos, contagem = np.unique(arr,return_counts=True)

print(f"Elementos únicos : {elementos_unicos}")
print(f"Contagem : {contagem}")



Gerando número aleatório entre 0 e 10 : 3
Delimitando o sorteio(1 a 10,10 números) : [7 7 1 9 5 8 1 1 8 2]
Transformando em um conjunto : {np.int64(1), np.int64(2), np.int64(5), np.int64(7), np.int64(8), np.int64(9)}
Transformando em um conjunto(usando numpy) : [1 2 5 7 8 9] 
Elementos únicos : [1 2 5 7 8 9]
Contagem : [3 1 1 2 2 1]
