Aula 4(Parte 1) - Numpy

-Usa estrutura própria ndArray(Numpy Array), usa normalmente tuplas e listas

-Numpy é muito otimizado(usa C no backend)

In [ ]:
import numpy as np
#Importando biblioteca numpy

In [ ]:
cont = 0
dados = {}

while(cont<3):
  nome = str(input("Nome : "))
  peso = float(input("Peso : "))
  dados[nome] = peso
  cont+=1
  mais_pesado = max(dados, key = dados.get)
  mais_leve = min(dados, key = dados.get)

print(f"Mais pesado : {mais_pesado}")
print(f"Mais leve : {mais_leve}")


Nome : faria
Peso : 40
Nome : jajajaja
Peso : 10
Nome : dassfafdasfdsfafafads
Peso : 50000
Mais pesado : dassfafdasfdsfafafads
Mais leve : jajajaja


In [ ]:
arr = np.array([10,20,30,40,50,60])
print(type(arr))
print(arr)
print(f"tamanho array : {arr.size}")
print(f"Dimensões do array(1,2,3) : {arr.ndim}")
print(f"Formato do array(3 x 2, 1 x 0) : {arr.shape} ")

mtz = np.array([[10,20],
                [30,40],
                [50,60]])
print(type(mtz))
print(f"Matriz : \n{mtz}")
print(f"tamanho matriz : {mtz.size}")
print(f"Dimensões da matriz : {mtz.ndim}")
print(f"Formato da matriz : {mtz.shape}")

Funções pré-prontas

In [ ]:
mtz = np.ones([5,5])
print(f"Matriz de um :  \n{mtz}")

mtz_zeros = np.zeros([5,5])
print(f"Matriz de zeros : \n{mtz_zeros}")

mtz_eye = np.eye(5)
print(f"Matriz identidade : \n{mtz_eye}")

arr = np.zeros([10])
print(arr.reshape([5,2]))

print(f"Array : {arr}")
print(f"Array transformado em matriz : {arr}")

mtz = np.arange(2,21,2)
print(f"Array de 2 a 20 de 2 em 2 : {mtz}")

print(f"Array transformado em matriz :  \n{mtz.reshape(2,5)}")




Operações entre Numpy arrays

In [ ]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([1,2,3,4,5])

print(f"Soma : {arr1 + arr2}") # ou arr3 = arr1 + arr2
print(f"Subtração : {arr1 - arr2}")
print(f"Multiplicação : {arr1 * arr2}")
print(f"Divisão : {arr1 / arr2}")
print(f"Potência : {arr1 ** arr2}")
print(f"Raiz quadrada : {np.sqrt(arr1)}")
print(f"Exponencial : {np.exp(arr1)}")
print(f"Logaritmo : {np.log(arr1)}")

arr3 = np.concatenate([arr1,arr2])
print(f"Arrays concatenados : {arr3}")

print(f"Escalar vezes o array : {2 * arr1}") # Broadcasting







In [ ]:
mtz = np.arange(10,96,5)
print(f"Array gerado : {mtz}")
print(f"Array transformada em matriz  : \n{mtz.reshape(3,6)}")
mtz = mtz.reshape(3,6)

#Extraindo soma das colunas
print(f"Soma colunas  : {mtz.sum(axis=0)}")

print(f"Soma linhas  : {mtz.sum(axis=1)}")

print(f"Soma primeira coluna : {mtz.sum(axis=0)[0]}")

print(f"Soma segunda linha : {mtz.sum(axis=1)[1]}")

print(f"Média das colunas : {mtz.mean(axis=0)}")

print(f"Média das linhas : {mtz.mean(axis=1)}")

print(f"Pegando soma de segunda coluna em diante : {mtz.sum(axis = 0)[1:,]}")

print(f"Pegando soma de segunda linha em diante : {mtz.sum(axis = 1)[1:,]}")







Núemros aleatórios no Numpy

In [ ]:
np.random.seed(5)
#Coloca uma semente que garante que os números serão os mesmos para todas máquinas
arr = np.random.randint(10)
print(f"Gerando número aleatório entre 0 e 10 : {arr}")

arr = np.random.randint(1,10,10)

print(f"Delimitando o sorteio(1 a 10,10 números) : {arr}")

print(f"Transformando em um conjunto : {set(arr)}")

print(f"Transformando em um conjunto(usando numpy) : {np.unique(arr)} ")

elementos_unicos, contagem = np.unique(arr,return_counts=True)

print(f"Elementos únicos : {elementos_unicos}")
print(f"Contagem : {contagem}")



Aula 4 (Parte 2) - Slicing no NumPy

In [ ]:
import numpy as np

In [ ]:
np.random.seed(10)
mtz = np.random.randint(1,99,9).reshape(3,3)
print(f"Matriz gerada : \n{mtz}")

print(f"Extraindo apenas segunda linha :  \n{mtz[1]}")

print(f"Extraindo apenas terceira coluna : \n{mtz[:,2]}")


print(f"Extraindo apenas submatriz 2x2 canto inferior esquerdo : {mtz[1:,1:]} ")



Matriz gerada : 
[[10 16 65]
 [29 90 94]
 [30  9 74]]
Matriz gerada : 
[[ 9 15 64]
 [28 89 93]
 [29  8 73]]
Extraindo apenas segunda linha :  
[29 90 94]
Extraindo apenas terceira coluna : 
[65 94 74]
Extraindo apenas submatriz 2x2 canto inferior esquerdo : [[90 94]
 [ 9 74]] 


Condicionais no NumPy

In [ ]:
#Pegnado elementos menores que 70

print(f"Elementos menores que 70 : \n{mtz[mtz<70]}")
#ou print(f"Elementos menores que 70(true) \n{mtz < 70})

print(f"Elementos pares : \n{mtz[mtz%2==0]}")
#ou print(f"Elementos pares : \n{mtz%2==0}")



Elementos menores que 70 : 
[10 16 65 29 30  9]
Elementos pares : 
[10 16 90 94 30 74]


Análise de padrões textuais com NumPy

In [ ]:
array = np.array(["Inatel","Casa Viva","ICC","CDG","eHealth","CSILab","RobotBulls","ProdLab","CRA","CRR"])
print(f"Array de strings : \n{array}")

#Submodulo do NumPy para trabalhar com textos

print(f"Posição do A nos elementos que tem a : {np.char.find(array,"a")}")
print(f"Booleana dos elementos com a : {np.char.find(array,"a") > 0}")
print(f"Elementos com a : {array[np.char.find(array,"a") > 0]}")
cond = np.char.find(array,"a") >= 0 # guarda em variável
print(f"Elementos com a(usando variável) : {array[cond]}")

print(f"Deixando todos elementos em maiúsculo : {np.char.upper(array)} ")
print(f"Deixando todos elementos em minúsculo : {np.char.lower(array)} ")
print(f"Deixando apenas a primeira letra maiúscula : {np.char.title(array)} ")
# -1 não tem, x posição do primeiro a



Array de strings : 
['Inatel' 'Casa Viva' 'ICC' 'CDG' 'eHealth' 'CSILab' 'RobotBulls'
 'ProdLab' 'CRA' 'CRR']
Posição do A nos elementos que tem a : [ 2  1 -1 -1  3  4 -1  5 -1 -1]
Booleana dos elementos com a : [ True  True False False  True  True False  True False False]
Elementos com a : ['Inatel' 'Casa Viva' 'eHealth' 'CSILab' 'ProdLab']
Elementos com a(usando variável) : ['Inatel' 'Casa Viva' 'eHealth' 'CSILab' 'ProdLab']
Deixando todos elementos em maiúsculo : ['INATEL' 'CASA VIVA' 'ICC' 'CDG' 'EHEALTH' 'CSILAB' 'ROBOTBULLS'
 'PRODLAB' 'CRA' 'CRR'] 
Deixando todos elementos em minúsculo : ['inatel' 'casa viva' 'icc' 'cdg' 'ehealth' 'csilab' 'robotbulls'
 'prodlab' 'cra' 'crr'] 
Deixando apenas a primeira letra maiúscula : ['Inatel' 'Casa Viva' 'Icc' 'Cdg' 'Ehealth' 'Csilab' 'Robotbulls'
 'Prodlab' 'Cra' 'Crr'] 


Como importar sets no NUMPY

In [ ]:
dataset = np.loadtxt('sample_data/space.csv',delimiter = ';',dtype = 'str')
#print(dataset)

In [ ]:
#Extraindo colunas data set

print(f"Imrprimindo colunas : \n{dataset[0,:]}")

print(f"Apenas empresas e informações  : \n{dataset[:,1]}")

print(f"Apenas nome das empresas : \n{dataset[1:,1]}")

print(f"Empresas únicas :{np.unique(dataset[1:,1])}")

print(f"Contagem por empresas \n{np.unique(dataset[1:,1],return_counts = 'True')}")









Imrprimindo colunas : 
['\ufeffNum' 'Company Name' 'Location' 'Datum' 'Detail' 'Status Rocket'
 ' Cost' 'Status Mission']
Apenas empresas e informações  : 
['Company Name' 'SpaceX' 'CASC' ... 'US Navy' 'RVSN USSR' 'RVSN USSR']
Apenas nome das empresas : 
['SpaceX' 'CASC' 'SpaceX' ... 'US Navy' 'RVSN USSR' 'RVSN USSR']
Empresas únicas :['AEB' 'AMBA' 'ASI' 'Arianespace' "Arm??e de l'Air" 'Blue Origin' 'Boeing'
 'CASC' 'CASIC' 'CECLES' 'CNES' 'Douglas' 'EER' 'ESA' 'Eurockot' 'ExPace'
 'Exos' 'General Dynamics' 'IAI' 'ILS' 'IRGC' 'ISA' 'ISAS' 'ISRO' 'JAXA'
 'KARI' 'KCST' 'Khrunichev' 'Kosmotras' 'Land Launch' 'Landspace'
 'Lockheed' 'MHI' 'MITT' 'Martin Marietta' 'NASA' 'Northrop' 'OKB-586'
 'OneSpace' 'RAE' 'RVSN USSR' 'Rocket Lab' 'Roscosmos' 'SRC' 'Sandia'
 'Sea Launch' 'SpaceX' 'Starsem' 'ULA' 'US Air Force' 'US Navy' 'UT'
 'VKS RF' 'Virgin Orbit' 'Yuzhmash' 'i-Space']
Contagem por empresas 
(array(['AEB', 'AMBA', 'ASI', 'Arianespace', "Arm??e de l'Air",
       'Blue Origin', 'Boeing',